project:
  type: website
  output-dir: docs

website:
  title: "mu2718"
  site-url: "https://mu2718.github.io"
  google-analytics:
    tracking-id: "G-Q3G5J0PLVE"
    storage: cookies
  description: "mu2718's Blog"
  navbar:
    background: primary
    left:
      - text: Posts
        href: posts.qmd
      - about.qmd

    tools:
      - icon: github
        href: https://github.com/mu2718/
        text: "mu2718 on GitHub"
      - icon: rss
        href: posts.xml
        text: Blog RSS Feed

  repo-url: https://github.com/mu2718/gps-walkthrough/
  repo-actions: [issue]

format:
  html:
    theme: 
      light: cosmo
    highlight-style: breeze
    toc: False
    include-in-header: microanalytics.html




