project:
  type: website
  output-dir: docs

website:
  title: "mu2718"
  site-url: https://mu2718.github.io
  description: "Test description"
  navbar:
    right:
      - about.qmd
      - text: Posts
        href: posts.qmd
      - text: Series
        menu:
          - text: GPS Walkthrough
            href: posts.qmd#category=gps
      - icon: github
        href: https://github.com/mu2718/
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    highlight-style: github
    css: styles.css
    toc: True
    include-in-header: microanalytics.html


comments:
  giscus:
    repo: mu2718/mu2718.github.io




