project:
  type: website
  output-dir: docs

website:
  title: "mu2718"
  site-url: "https://mu2718.github.io"
  google-analytics:
    tracking-id: "G-Q3G5J0PLVE"
    storage: cookies
  description: "mu2718's Blog"
  navbar:
    background: primary
    right:
      - about.qmd
      - text: Posts
        href: posts.qmd
      - icon: github
        href: https://github.com/mu2718/
      - icon: rss
        href: posts.xml

format:
  html:
    theme: 
      light: cosmo
    highlight-style: github
    toc: False
    include-in-header: microanalytics.html

comments:
  giscus:
    repo: mu2718/mu2718.github.io




